version: 3

services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: py manage.py runserver 0.0.0.0:8000
        ports:
            -8000:8000
   